rackerlabs/cloudfeeds-nabu

- tiamat/build.gradle
- tiamat/src/main/scala/com/rackspace/feeds/archives/Archiver.scala
- tiamat/src/main/scala/com/rackspace/feeds/archives/Tiamat.scala
- tiamat/src/main/scala/com/rackspace/feeds/archives/XmlProcessing.scala
- tiamat/src/main/scala/com/rackspace/feeds/archives/util/createHiveInput.scala
- tiamat/src/test/scala/com.rackspace.feeds.archives/ArchiverTest.scala
- tiamat/src/test/scala/com.rackspace.feeds.archives/CreateFilesFeedTest.scala
Tested spark 1.2 on our test node & updated code to order entries by datelastupdated timestamp.
Please first accept:  https://github.com/rackerlabs/cloudfeeds-nabu/pull/8
> Cf 548 - Investigate spark 1.2 to allow order by timestamp

- usmu/build.gradle
- usmu/src/main/resources/usmu-install-to-hdfs.sh
A few install/deploy issues I came across while testing Usmu in public cloud:
*) RPM did not contain any of the *.ddl file
*) Install script incorrectly still referenced the Preferences Svc workflow, which we decided not to use
> CF-584: minor fixes: include *.ddl files in RPM, comment out unneeded prefs workflow

- usmu/src/main/resources/feedsImport-wf.xml
- usmu/src/main/resources/usmu-coord-run.sh
- usmu/src/main/resources/usmu-coordinator.properties
- usmu/src/main/resources/usmu-coordinator.xml
Changes to support a more seamless integration with Tiamat and to support monitoring:
* add a workflow fs action to create an empty ```success.txt``` file on successful run of the daily workflow
* add configuration for the top directory location in HDFS for the success file in the *.properties file
* change default values of some locations to /user/cloudfeeds
> CF-703: create success.txt file on successful daily run of Usmu workflow

- common.gradle
Cloud Feeds archiving should not be grouped under prefs. What do you guys think?
> change groupId

- usmu/build.gradle
- usmu/src/main/resources/monitor-feeds_dump.sh
- usmu/src/main/resources/monitor-prefs_dump.sh
- usmu/src/main/resources/monitor-usmu.sh
Add monitor shell scripts for hadoop success files for 
* feeds dump from ballista (monitor-feeds_dump.sh),
* preference service dump from ballista (monitor-prefs_dump.sh), and 
* usmu processing run (monitor-usmu.sh)
monitor-feeds_dump.sh and monitor-usmu.sh requires a region (DFW, ORD, IAD, LON, HKG, SYD), while monitor-prefs_dump.sh does not.  All three will check for the success file of yesterday run, if the shell script is executed within a time window.
The monitor-prefs_dump.sh is written with the assumption that the success file will be stored in the hadoop fs path "/user/cloudfeeds/prefs_dump/_$yesterday/_SUCCESS" (note the underscore before $yesterday date value), which will be played in the near future.  
See Greg's comment in the Archiving Monitoring and Alerting wiki: …
> CF-836 Implement monitoring for Archiving apps

- tiamat/src/main/scala/com/rackspace/feeds/archives/CreateFilesFeed.scala
- tiamat/src/test/scala/com.rackspace.feeds.archives/CreateFilesFeedTest.scala
The changes are:
When we build archived pages in customers' Cloud Files containers, we currently set the self, prev-archive, and next-archive links to the container URLs that are specified in the customers' Preferences. We want to replace this with Cloud Feeds endpoints https://feeds.endpoints/archive/nastId/containerName.
> CF-721: set self/prev/next archive links to point to Feeds endpoints

- tiamat/src/main/scala/com/rackspace/feeds/archives/Options.scala
- tiamat/src/test/scala/com.rackspace.feeds.archives/OptionsTest.scala
- Added option --all-tenants to process all tenants
- Options --all-tenants and --tenants are mutually exclusive and atleast one of them have to be present.
> [CF-889] Require additional options to process all tenants

- usmu/src/main/resources/entries.hive.ddl
This script is now being run on the deployment. Which means, if the table to be created already exists, it should not fail.
> CF-1032: make this script idempotent

- tiamat/src/main/resources/reference.conf
- tiamat/src/main/scala/com/rackspace/feeds/archives/Archiver.scala
Two fixes:
- removing list of regions from the reference.conf to allow tiamat to run environments with fewer regions (e.g., test & staging)
- updating tiamat to handle null values in any string fields in the db (all non-string fields will never be null as per postgres schema).
NOTE:  Some string fields are declared as NOT NULL in postgress and don't need the check, but i added anyway.   Let me know if you want to remove it.
> NULL values in db solution, update tiamat reference.conf

- tiamat/src/main/resources/log4j.properties
When you run Tiamat manually, you will see logging going out to stdout. I don't think this is useful as things scroll by fast on the screen and I can't search for a specific things. 
When you run Tiamat from cron, cron will save all the output and mail it to the user. As a result, cloudfeeds user will get email everytime Tiamat runs. This may be flooding cloudfeeds user mailbox. Someone has to remember to delete those emails.
So this PR turns off console logging :-) for Tiamat.
> turn off console logging for Tiamat

- tiamat/src/main/scala/com/rackspace/feeds/archives/CreateFilesFeed.scala
According to Cloud Files documentation here:
http://docs-internal.rackspace.com/files/api/v1/cf-devguide/content/PUT_createcontainer_v1__account___container__containerServicesOperations_d1e000.html
it's possible Cloud Files will return HTTP code 202 when the container to be created is already there.
> CF-1054: expect 202 from Files

- tiamat/src/main/resources/reference.conf
- tiamat/src/main/resources/tiamat.conf
- tiamat/src/main/scala/com/rackspace/feeds/archives/Options.scala
- tiamat/src/main/scala/com/rackspace/feeds/archives/Tiamat.scala
- tiamat/src/test/resources/test.conf
- tiamat/src/test/scala/com.rackspace.feeds.archives/OptionsTest.scala
I'll also have a PR to our ansible project to update the tiamat.conf generation to add the new test-related fields.
> CF-1105 - add --test-run switch to tiamat to enable testing

- tiamat/src/main/resources/tiamat.sh
- tiamat/src/main/scala/com/rackspace/feeds/archives/Tiamat.scala
This mechanism of overwriting the log configuration for Spark:
```
--conf "spark.driver.extraJavaOptions=-Dlog4j.configuration=file:/etc/cloudfeeds-nabu/tiamat/log4j.properties"
```
does not work on HDP 2.2.4 and HDP 2.2.6.
I found this article in StackOverflow:
http://stackoverflow.com/questions/28840438/how-to-override-sparks-log4j-properties-per-driver/31565963#31565963
The option ```   --driver-java-options "-Dlog4j.configuration=file:///etc/cloudfeeds-nabu/tiamat/log4j.properties"``` works great! I tested it in both HDP 2.2.4 and HDP 2.2.6.
The only thing that's a bit weird is that when you run tiamat and tiamat got an error, the stack trace is printed out to stdout/stderr (not logging). Like this:
```
[cloudfeeds@gateway-1 bin]$  sh tiamat.sh --dates 2015-07-22 -t 5914283
Spark …
```
> CF-1053: clean up tiamat log

- usmu/src/main/resources/usmu-coord-run.sh
- usmu/src/main/resources/usmu-coord-stop.sh
Change script so that when we stop/kill previously running coordinator jobs, we only kill those jobs with the name FeedsImport-$region. The $region variable will come from the REGION_LIST in the usmu-coordinator.properties file.
> CF-1186: kill coordinator jobs only with certain names (ours)

- tiamat/build.gradle
Adding tiamat jar as artifact published to maven
After this is accepted I'd like to cut a new release of nabu so I could verify my usage-schema work against the published jar.
> CF-541 - Ensure Tiamat is kept in synch with standard-usage-schema

- tiamat/src/main/scala/com/rackspace/feeds/archives/Preferences.scala
- tiamat/src/test/scala/com.rackspace.feeds.archives/PreferencesTest.scala
Fix a bug that prevented the following
- when no default container is configured for a tenant
and a subset of regions are archived (using tiamat's -r option)
- Only the request region is archived for the tenant
> CF-1260 - Tiamat does not honor -r setting

- tiamat/build.gradle
- tiamat/src/main/resources/log4j-local.properties
- tiamat/src/main/resources/log4j.properties
- tiamat/src/main/resources/tiamat.sh
Updated logging to enable the following:
- The local driver app writes logs to /var/cloudfeeds-nabu/tiamat/tiamat.log*
- The executors log to the application log on HDFS
Enabled this by adding a local log4j file, and a general log4j file
which writes to the HDFS appplication log
> CF-1219 - Tiamat logging.

- tiamat/src/main/resources/nonStringAttrs.xsl
This PR updates the `nonStringAttrs.xsl` file to incorporate a new Neutron schema.
See: https://jira.rax.io/browse/CF-1349
See: https://github.com/rackerlabs/standard-usage-schemas/pull/580
> CF-1349: update nonStringAttrs.xsl due to new neutron schema

- tiamat/src/main/resources/nonStringAttrs.xsl
Somehow the lbaas attribute never got added from a previous PR (https://github.com/rackerlabs/standard-usage-schemas/pull/579).  Not sure how that slipped through.  github reports that the PR checks passed.
> adding new attributes from standard usage schemas

- tiamat/src/main/resources/nonStringAttrs.xsl
Previously, I create lbaas uptime schema and lbaas connections schema.
Prod wants to add bandwidth usage and consolidate bandwdith, uptime and connections in a single event.
> add lbaas2, remove lbaas-connections

- tiamat/build.gradle
Updating to spark 1.6 to match the new version of Hadoop on the caspian cluster.
> updating to spark 1.6

- tiamat/src/main/resources/nonStringAttrs.xsl
Syncing nonStringAttrs.xsl to match the one in standard-usage-schemas after adding the new Ticketing search.
> Syncing nonStringAttrs.xsl for new Ticketing search

- tiamat/src/main/resources/nonStringAttrs.xsl
Synced nonStringAttrs.xsl to update ticketing/queue/view to reflect that product/@number is now a string (used to be an int).
> Synced nonStringAttrs.xsl for ticketing feed update

- tiamat/src/main/resources/nonStringAttrs.xsl
Updated nonStringAttrs.xsl to match standard-usage-schemas after adding the new One Queue View feed.
> Syncing nonStringAttrs.xsl for new One Queue View feed

- tiamat/src/main/resources/nonStringAttrs.xsl
Syncing the `nonStringAttrs.xsl` change from the Standard Usage Schema repo to this repo.
https://github.com/rackerlabs/standard-usage-schemas/pull/642
> Synced nonStringAttrs.xsl for Support feed update

- tiamat/src/main/resources/nonStringAttrs.xsl
Syncing the `nonStringAttrs.xsl` change from the Standard Usage Schema repo to this repo.
https://github.com/rackerlabs/standard-usage-schemas/pull/648
> Synced nonStringAttrs.xsl for new User Integration feed

- tiamat/src/main/resources/nonStringAttrs.xsl
Syncing the `nonStringAttrs.xsl` change from the Standard Usage Schema repo to this repo.
https://github.com/rackerlabs/standard-usage-schemas/pull/656
> Synced nonStringAttrs.xsl for Support Team updates

- tiamat/src/main/resources/nonStringAttrs.xsl
Ran `mvn clean initialize` on [schema](https://github.com/rackerlabs/standard-usage-schemas) and re-generated xsl. Syncing change for release prep.
> nonStringAttrs.xsl generated file update for 135 release
